# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'Teamwork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Teamwork

#pod 'RealmSwift'
#pod 'Realm'

pod 'RealmSwift'
pod 'RealmMapView', :git => 'https://github.com/bigfish24/ABFRealmMapView.git'
pod 'RealmLoginKit'
pod 'Eureka', :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
pod 'ImageRow'
pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git'
pod 'JVFloatLabeledTextField'
pod 'ActionSheetPicker-3.0'
pod 'ISHHoverBar'
pod 'ReachabilitySwift'
pod 'Alertift', '~> 1.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'PKHUD', '~> 4.0'


#pod 'BTNavigationDropdownMenu', :git => 'https://github.com/PhamBaTho/BTNavigationDropdownMenu.git', :branch => 'swift-3.0'
# We forked this to support manual selection of menu items - which includes fixes/competion of #code from
# commit: https://github.com/PhamBaTho/BTNavigationDropdownMenu/pull/108/commits/0139a13bb1fe4130d5f035da709dcc70f8052177 
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/realm-demos/BTNavigationDropdownMenu', :branch => 'swift-3.0'


  target 'TeamworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
