# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'



target 'Teamwork' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# Pods for Teamwork


pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :submodules => true #:branch => 'master'
pod 'RealmLoginKit', :path => '../../realm-loginkit/RealmLoginKit Apple'

#pod 'RealmMapView',  :git => 'https://github.com/bigfish24/ABFRealmMapView.git', :branch => 'af/realm-3.0'

pod 'Eureka',  :git => 'https://github.com/xmartlabs/Eureka.git', :branch => 'feature/Xcode9-Swift3_2'
pod 'ImageRow'	#, '~> 2.0'
pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git'
pod 'JVFloatLabeledTextField'
pod 'ActionSheetPicker-3.0'
pod 'ISHHoverBar'
pod 'ReachabilitySwift'
pod 'Alertift', '~> 2.0'
pod 'Fabric'
pod 'Crashlytics'
pod 'PKHUD', '~> 4.0'
pod 'BTNavigationDropdownMenu', :git => 'https://github.com/realm-demos/BTNavigationDropdownMenu', :branch => 'swift-3.0'


  target 'TeamworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
